### ISSUE TITLE
"BrokenPipeError: [Errno 32] Broken pipe" when reloading client webpage

### ISSUE THREAD

**Issue by AimbotNooby** [Pithikos/python-websocket-server#111]
Hi, when I reload or close my client page the following Error comes up.
Btw, I have a loop in my function, which is called when a message is received. 
An similar error is coming on windows: https://github.com/Pithikos/python-websocket-server/issues/110 
```
Traceback (most recent call last):
  File "/usr/lib/python3.9/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.9/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/pi/.local/lib/python3.9/site-packages/websocket_server/websocket_server.py", line 271, in __init__
    StreamRequestHandler.__init__(self, socket, addr, server)
  File "/usr/lib/python3.9/socketserver.py", line 720, in __init__
    self.handle()
  File "/home/pi/.local/lib/python3.9/site-packages/websocket_server/websocket_server.py", line 284, in handle
    self.read_next_message()
  File "/home/pi/.local/lib/python3.9/site-packages/websocket_server/websocket_server.py", line 341, in read_next_message
    opcode_handler(self, message_bytes.decode('utf8'))
  File "/home/pi/.local/lib/python3.9/site-packages/websocket_server/websocket_server.py", line 163, in _message_received_
    self.message_received(self.handler_to_client(handler), self, msg)
  File "/home/pi/Desktop/dartsllerWebsocket.py", line 40, in message_received
    server.send_message_to_all("Test"+","+"test"+","+str(t1))
  File "/home/pi/.local/lib/python3.9/site-packages/websocket_server/websocket_server.py", line 81, in send_message_to_all
    self._multicast(msg)
  File "/home/pi/.local/lib/python3.9/site-packages/websocket_server/websocket_server.py", line 199, in _multicast
    self._unicast(client, msg)
  File "/home/pi/.local/lib/python3.9/site-packages/websocket_server/websocket_server.py", line 195, in _unicast
    receiver_client['handler'].send_message(msg)
  File "/home/pi/.local/lib/python3.9/site-packages/websocket_server/websocket_server.py", line 344, in send_message
    self.send_text(message)
  File "/home/pi/.local/lib/python3.9/site-packages/websocket_server/websocket_server.py", line 413, in send_text
    self.request.send(header + payload)
BrokenPipeError: [Errno 32] Broken pipe
```

**Comment by AimbotNooby** [comment]
I tried solving it by following this [Webpage](https://linuxpip.org/broken-pipe-python-error/#Avoid_Errno_32_Broken_pipe_by_ignoring_SIGPIPE:~:text=from%20signal%20import%20signal%2C%20SIGPIPE%2C%20SIG_DFL%20%0A%23Ignore%20SIG_PIPE%20and%20don%27t%20throw%20exceptions%20on%20it...%20(http%3A//docs.python.org/library/signal.html)%0Asignal(SIGPIPE%2CSIG_DFL)), but now another error occurs.
`Backend terminated or disconnected. Use 'Stop/Restart' to restart.`

**Comment by TheTechRobo** [comment]
Broken pipe errors  occur when a connection is lost. It's a normal error if you don't disconnect gracefully.

**Comment by kazar4** [comment]
Is there a way to handle this for connections that don't disconnect gracefully? Like a way to check without it crashing
