### ISSUE TITLE
Non utf8 issues

### ISSUE THREAD

**Issue by Revencu** [Pithikos/python-websocket-server#34]
`Traceback (most recent call last):
  File "c:\python27\lib\SocketServer.py", line 596, in process_request_thread
    self.finish_request(request, client_address)
  File "c:\python27\lib\SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "c:\python27\lib\site-packages\websocket_server\websocket_server.py", line 136, in __init__
    StreamRequestHandler.__init__(self, socket, addr, server)
  File "c:\python27\lib\SocketServer.py", line 652, in __init__
    self.handle()
  File "c:\python27\lib\site-packages\websocket_server\websocket_server.py", line 147, in handle
    self.handshake()
  File "c:\python27\lib\site-packages\websocket_server\websocket_server.py", line 243, in handshake
    message = self.request.recv(1024).decode().strip()
UnicodeDecodeError: 'ascii' codec can't decode byte 0xa0 in position 4: ordinal not in range(128)`
How resolve this?

**Comment by Pithikos** [comment]
It would help to to give some example code and what you were trying to do..
