### ISSUE TITLE
Exception from the websocket_server

### ISSUE THREAD

**Issue by Speedy2k** [Pithikos/python-websocket-server#82]
Hi, i got those exceptions from the websocket_server that mek it stop running and dont send data anymore:

Exception happened during processing of request from ('198.108.67.48', 64850)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 599, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/pi/.local/lib/python2.7/site-packages/websocket_server/websocket_server.py", line 168, in __init__
    StreamRequestHandler.__init__(self, socket, addr, server)
  File "/usr/lib/python2.7/SocketServer.py", line 655, in __init__
    self.handle()
  File "/home/pi/.local/lib/python2.7/site-packages/websocket_server/websocket_server.py", line 179, in handle
    self.handshake()
  File "/home/pi/.local/lib/python2.7/site-packages/websocket_server/websocket_server.py", line 313, in handshake
    headers = self.read_http_headers()
  File "/home/pi/.local/lib/python2.7/site-packages/websocket_server/websocket_server.py", line 302, in read_http_headers
    assert http_get.upper().startswith('GET')
AssertionError
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('198.108.67.48', 1462)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 599, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/pi/.local/lib/python2.7/site-packages/websocket_server/websocket_server.py", line 168, in __init__
    StreamRequestHandler.__init__(self, socket, addr, server)
  File "/usr/lib/python2.7/SocketServer.py", line 655, in __init__
    self.handle()
  File "/home/pi/.local/lib/python2.7/site-packages/websocket_server/websocket_server.py", line 179, in handle
    self.handshake()
  File "/home/pi/.local/lib/python2.7/site-packages/websocket_server/websocket_server.py", line 316, in handshake
    assert headers['upgrade'].lower() == 'websocket'
KeyError: 'upgrade'
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('198.108.67.48', 2034)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 599, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/pi/.local/lib/python2.7/site-packages/websocket_server/websocket_server.py", line 168, in __init__
    StreamRequestHandler.__init__(self, socket, addr, server)
  File "/usr/lib/python2.7/SocketServer.py", line 655, in __init__
    self.handle()
  File "/home/pi/.local/lib/python2.7/site-packages/websocket_server/websocket_server.py", line 179, in handle
    self.handshake()
  File "/home/pi/.local/lib/python2.7/site-packages/websocket_server/websocket_server.py", line 313, in handshake
    headers = self.read_http_headers()
  File "/home/pi/.local/lib/python2.7/site-packages/websocket_server/websocket_server.py", line 301, in read_http_headers
    http_get = self.rfile.readline().decode().strip()
UnicodeDecodeError: 'ascii' codec can't decode byte 0x89 in position 4: ordinal not in range(128)
----------------------------------------

**Comment by syedsalmanalam1** [comment]
I am having the same issue

**Comment by chintanpbhatt** [comment]
Also getting the same error on Python 3.x

AssertionError
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 49840)
Traceback (most recent call last):
  File "/usr/lib64/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib64/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 271, in __init__
    StreamRequestHandler.__init__(self, socket, addr, server)
  File "/usr/lib64/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/usr/local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 282, in handle
    self.handshake()
  File "/usr/local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 434, in handshake
    headers = self.read_http_headers()
  File "/usr/local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 423, in read_http_headers
    assert http_get.upper().startswith('GET')
AssertionError
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 53466)
Traceback (most recent call last):
  File "/usr/lib64/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib64/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 271, in __init__
    StreamRequestHandler.__init__(self, socket, addr, server)
  File "/usr/lib64/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/usr/local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 282, in handle
    self.handshake()
  File "/usr/local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 434, in handshake
    headers = self.read_http_headers()
  File "/usr/local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 423, in read_http_headers
    assert http_get.upper().startswith('GET')
AssertionError
