### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by kesavanpuc** [Pithikos/python-websocket-server#83]
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 49100)
Traceback (most recent call last):
  File "/usr/lib/python3.8/socketserver.py", line 720, in __init__
    self.handle()
  File "/home/kesavan/Documents/eros/django/cb/web_chatbot/ws/python-websocket-server/websocket_server/websocket_server.py", line 179, in handle
    self.handshake()
  File "/home/kesavan/Documents/eros/django/cb/web_chatbot/ws/python-websocket-server/websocket_server/websocket_server.py", line 316, in handshake
    assert headers['upgrade'].lower() == 'websocket'
KeyError: 'upgrade'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/kesavan/Documents/eros/django/cb/web_chatbot/ws/python-websocket-server/websocket_server/websocket_server.py", line 168, in __init__
    StreamRequestHandler.__init__(self, socket, addr, server)
  File "/usr/lib/python3.8/socketserver.py", line 722, in __init__
    self.finish()
  File "/home/kesavan/Documents/eros/django/cb/web_chatbot/ws/python-websocket-server/websocket_server/websocket_server.py", line 350, in finish
    self.server._client_left_(self)
  File "/home/kesavan/Documents/eros/django/cb/web_chatbot/ws/python-websocket-server/websocket_server/websocket_server.py", line 147, in _client_left_
    self.client_left(client, self)
  File "server.py", line 11, in client_left
    print("Client(%d) disconnected" % client['id'])
TypeError: 'NoneType' object is not subscriptable
----------------------------------------

**Comment by Pithikos** [comment]
I close this for now since many fixes have been done and this potentially has been covered. If it still persists please re-open or raise a new issue.

**Comment by kesavanpuc** [comment]
ok
