### ISSUE TITLE
TypeError: str, bytes or bytearray expected, not int

### ISSUE THREAD

**Issue by urb31075** [Pithikos/python-websocket-server#97]
urb@san:~/python-websocket-server$ python3 server.py
Traceback (most recent call last):
  File "server.py", line 22, in <module>
    server = WebsocketServer(PORT)
  File "/home/urb/python-websocket-server/websocket_server/websocket_server.py", line 117, in __init__
    TCPServer.__init__(self, (host, port), WebSocketHandler)
  File "/usr/lib/python3.8/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/usr/lib/python3.8/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
TypeError: str, bytes or bytearray expected, not int

**Comment by Diegocndd** [comment]
Put quotation marks around the port. It worked for me.

**Comment by MuRongPIG** [comment]
```python3
PORT=9001
server = WebsocketServer(PORT)
```
the bug is here (line 21,22).
plz change it into:
```python3
PORT=9001
server = WebsocketServer(port=PORT)
```

maybe I'll pull request to solve it.

**Comment by Pithikos** [comment]
Solved. Fix will be included in next release.
